anaconda 5.2.0-3: 	* new: update script for Anaconda 	* new propeties: 		* update_dry_run - update in 'dry-run' mode 		* update_verbose - make update verbose 		* update_skip - skip update (only on setup) 		* log_level 	* changelog outsourced from control.in (combined again in final control file) 	* use dotNet4 version of psDetail for Windows 10 	* new parameter for Makefile: KEEPFILES 	* modified preinst/postinst for KEEPFILES 	* fix restore custom directories in postinst (improved) 	* adjusted postinst for changed $SRC directory (only valid for MPIMSP) 	* make target "download" creates md5sums for archives 	* check md5sums of archives in self download packages 	* maintainer defined in spec 	* fixed download section in makefile 	* fixed creation of desktop link (for paths with withespace) 	* fixed checkinstance.opsiinc: $PSDETAIL$ is already set 	* wait for hidden uninstaller Un_A.exe

diff --git a/SRC/OPSI/postinst.in b/SRC/OPSI/postinst.in
--- a/SRC/OPSI/postinst.in
+++ b/SRC/OPSI/postinst.in
@@ -10,9 +10,10 @@
 #   PRODUCT_ID: id of the current product
 #   CLIENT_DATA_DIR: directory which contains the installed client data
 #=====================================================================
-# J. Boettge <boettge@mpi-halle.mpg.de>	2018-02-19 18:05:48 +0100
+# J. Boettge <boettge@mpi-halle.mpg.de>	2018-06-22 11:58:55 +0200
 #=====================================================================
 
+TS=$(date +"%s")
 LOGFILE={{O_INST_LOG}}
 
 exec >> $LOGFILE
@@ -21,27 +22,30 @@ chgrp opsiadmin $LOGFILE
 chmod g+rw $LOGFILE
 
 echo "=================================================="
-echo "${PRODUCT_ID} POSTINST LOG"
+echo "${PRODUCT_ID} ({{ORGNAME}}) POSTINST LOG"
 echo "=================================================="
+date +'Start: %F  %H:%M:%S'
 
-SRC="${CLIENT_DATA_DIR}/../../source/${PRODUCT_ID##0_}"
+SRC="${CLIENT_DATA_DIR}/../_SOURCE/${PRODUCT_ID##0_}"
 DST="${CLIENT_DATA_DIR}/files"
 # remove trailing "/" in path:
 DST=${DST%\/}
+TMP_DIR=${CLIENT_DATA_DIR}/../${PRODUCT_ID}.tmp
 ERR=0
 
 ### check for testing and DFN package:
 P=${PRODUCT_ID}
-[ "${P}" = "${P##0_}" ] &&  IS_TESTING=false || IS_TESTING=true
+[ "${P}" = "${P##0_}" -a "${P}" = "${P##test_}" ] &&  IS_TESTING=false || IS_TESTING=true
 P=${P/#0_/}
+P=${P/#test_/}
 [ "${P}" = "${P##dfn_}" ] && IS_DFN=false || IS_DFN=true
 
 
 if [ $IS_DFN == true ]; then
-	 [ ! -d "${DST}" ] && mkdir $DST
+	 [ ! -d "${DST}" -a ! -d $TMP_DIR/files ] && mkdir $DST
 else
-	### symlink files directory to ../../source/${PRODUCT_ID##0_} only
-	### for non-DFN packages:
+	### symlink files directory to ../_SOURCE/${PRODUCT_ID##0_}
+	### only for non-DFN packages:
 	if [ -h "${DST}" ]; then
 		echo "Symlink to [${DST}] already exists. - Replacing"
 		rm ${DST}
@@ -63,16 +67,33 @@ fi
 
 
 ### restore custom directories
-TMP_DIR=${CLIENT_DATA_DIR}/../${PRODUCT_ID}.tmp
 if [ -d $TMP_DIR ]; then
 	echo 'Restoring previous directories...'
-	
+	TMP_DIR=`realpath $TMP_DIR`
 	for DIRNAME in custom files; do
 		echo "* [${DIRNAME}]"
 		if [ -d $TMP_DIR/${DIRNAME} ]; then
-			test -e $CLIENT_DATA_DIR/${DIRNAME} && rm -rf $CLIENT_DATA_DIR/${DIRNAME}
+			test -e $CLIENT_DATA_DIR/${DIRNAME} || mkdir $CLIENT_DATA_DIR/${DIRNAME}
 			echo -e "\tmoving $TMP_DIR/${DIRNAME} to $CLIENT_DATA_DIR/"
-			mv $TMP_DIR/${DIRNAME} $CLIENT_DATA_DIR/ || exit 1	
+			
+			IFS=$'\n'
+			PR=$TMP_DIR/${DIRNAME}
+			for D in `find ${PR} -xtype d`; do 
+				if [ -n "${D##${PR}}" -a ! -d "$CLIENT_DATA_DIR/${DIRNAME}/${D##${PR}}" ]; then
+					TGT=$CLIENT_DATA_DIR/${DIRNAME}/${D##${PR}}
+					echo -e "\t* mdir [${D##${PR}}] --> [${TGT}]"
+					mkdir -p "${TGT}"
+				fi
+			done &&\
+			for F in `find ${PR} -xtype f`; do
+				if [ -n "$F" -a ! -e "$CLIENT_DATA_DIR/${DIRNAME}/${F##${PR}/}" ]; then
+					echo -e "\t* fmov [${F##${PR}/}]"
+					mv "${F}" "$CLIENT_DATA_DIR/${DIRNAME}/${F##${PR}/}"
+				fi
+			done &&\
+			rm -rf $TMP_DIR/${DIRNAME} || exit 1
+			## rsync -av --remove-source-files $TMP_DIR/${DIRNAME}/. $CLIENT_DATA_DIR/${DIRNAME}/ && \
+			## rm -rf $TMP_DIR/${DIRNAME} || exit 1
 		else
 			echo -e "\tdoes not exist here"
 		fi
@@ -86,14 +107,17 @@ rm -rf $TMP_DIR
 {{#ifdef_auto_download}}
 ### product downloader
 if [[ -f "${CLIENT_DATA_DIR}/product_downloader.sh" ]]; then
-	echo "Calling product downloader"
+	echo -e "\nCalling product downloader"
 	DEST_DIR=${DST} ${CLIENT_DATA_DIR}/product_downloader.sh
 	ERR=$?
 else
-	echo "Product downloader not found!"
+	echo -e "\nProduct downloader not found!"
 	ERR=2
 fi
-exit $ERR
 {{/ifdef_auto_download}}
 {{/ifdef_allinc}}
 
+date +'Finish: %F  %H:%M:%S'
+TE=$(date +"%s")
+echo  "*** Script runtime: $(($TE - $TS)) seconds ***"
+exit $ERR
